name: CI/CD Pipeline with Security

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kod
        uses: actions/checkout@v4

      - name: Bygg Docker-image
        run: docker build -t dockerapp:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'dockerapp:${{ github.sha }}'
          ignore-unfixed: true
          trivyignores: '.trivyignore'

#      - name: Dependency Review (SCA)
#       uses: actions/dependency-review-action@v4
#        with:
#          fail-on-severity: high
